{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-ui",
    "version": "4.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy",
          "version": {
            "requires": "4.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-ui-4.15.0.aar",
          "url": "livebuy-ui-4.15.0.aar",
          "size": 256765,
          "sha512": "78bebaa54ed67d36ccf3c8992f8c226d80c7b76284ce6fd8eac88d288f748b75274e8983dea94a8c7a67d5d135582fd4f19e9f2215cd99d5831473cfc9b016e1",
          "sha256": "1d3ce49143c1ef0ea82b61357dbc3d8545ba3c58ad40055a197a7783273e0b44",
          "sha1": "011c68fc8481e0ce3309b9f4e32c434a255da241",
          "md5": "f8afa2ed6fe1332a582a5b6d3c0a5d8a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy",
          "version": {
            "requires": "4.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-ui-4.15.0.aar",
          "url": "livebuy-ui-4.15.0.aar",
          "size": 256765,
          "sha512": "78bebaa54ed67d36ccf3c8992f8c226d80c7b76284ce6fd8eac88d288f748b75274e8983dea94a8c7a67d5d135582fd4f19e9f2215cd99d5831473cfc9b016e1",
          "sha256": "1d3ce49143c1ef0ea82b61357dbc3d8545ba3c58ad40055a197a7783273e0b44",
          "sha1": "011c68fc8481e0ce3309b9f4e32c434a255da241",
          "md5": "f8afa2ed6fe1332a582a5b6d3c0a5d8a"
        }
      ]
    }
  ]
}
