{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy",
    "version": "4.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-4.6.2.aar",
          "url": "livebuy-4.6.2.aar",
          "size": 859213,
          "sha512": "c0d9916248ccd68377851ef9de8915f2c964707591b0843fb451873d727839038103c35faf8af4044af72776688e5e278ff53b84fc9220c08b795dedcaeef521",
          "sha256": "7703b738d47277c8b502dd706c7fc31612419405f058e94aff9a31aaa8f100a7",
          "sha1": "819f235a234dced0b12f3b8a3f48c215c5788647",
          "md5": "6db7cd256f44d927ef2be673708d3fea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-session",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "ivs-player",
          "version": {
            "requires": "1.52.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-4.6.2.aar",
          "url": "livebuy-4.6.2.aar",
          "size": 859213,
          "sha512": "c0d9916248ccd68377851ef9de8915f2c964707591b0843fb451873d727839038103c35faf8af4044af72776688e5e278ff53b84fc9220c08b795dedcaeef521",
          "sha256": "7703b738d47277c8b502dd706c7fc31612419405f058e94aff9a31aaa8f100a7",
          "sha1": "819f235a234dced0b12f3b8a3f48c215c5788647",
          "md5": "6db7cd256f44d927ef2be673708d3fea"
        }
      ]
    }
  ]
}
