{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-4.19.0.aar",
          "url": "livebuy-4.19.0.aar",
          "size": 871152,
          "sha512": "0710bc1aa2255e8d3a02859fdf9669271606ec9c49cfa8cac274af0d8e2c64799dd1fbeb0d5f484e8c052ce1fd66bc93d97de9860efe2e62149c907105ac6954",
          "sha256": "bbc7c92a8ee9ab998348e5daf494537eaa41e7c75aac468d038c7e26de8a0f9c",
          "sha1": "c222b457a44c80e4c29c01f665cbb118a5d3f654",
          "md5": "c6e7b3c7cb5c5732c7f6632f9e7477bb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-session",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "ivs-player",
          "version": {
            "requires": "1.52.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-4.19.0.aar",
          "url": "livebuy-4.19.0.aar",
          "size": 871152,
          "sha512": "0710bc1aa2255e8d3a02859fdf9669271606ec9c49cfa8cac274af0d8e2c64799dd1fbeb0d5f484e8c052ce1fd66bc93d97de9860efe2e62149c907105ac6954",
          "sha256": "bbc7c92a8ee9ab998348e5daf494537eaa41e7c75aac468d038c7e26de8a0f9c",
          "sha1": "c222b457a44c80e4c29c01f665cbb118a5d3f654",
          "md5": "c6e7b3c7cb5c5732c7f6632f9e7477bb"
        }
      ]
    }
  ]
}
