{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-3.2.2.aar",
          "url": "livebuy-reference-ui-3.2.2.aar",
          "size": 2392765,
          "sha512": "14082e909ad016e2ab51d7516bd36f2f0fcfda6d7bef5b54e954bb5fac49608a0787507f2c7fa6a65f459fcae5c2683ccfd2860940dcb1879cfd0f2499d85437",
          "sha256": "754687f4b477ca7736680f7f24105c5fb55898a5c3fd2141ac20a7a681889f71",
          "sha1": "b4b6fd14c1a36f2e9bdcf5196ae82eb29fc7730b",
          "md5": "270a47216a3548b5d53ea0188b83af6c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-3.2.2.aar",
          "url": "livebuy-reference-ui-3.2.2.aar",
          "size": 2392765,
          "sha512": "14082e909ad016e2ab51d7516bd36f2f0fcfda6d7bef5b54e954bb5fac49608a0787507f2c7fa6a65f459fcae5c2683ccfd2860940dcb1879cfd0f2499d85437",
          "sha256": "754687f4b477ca7736680f7f24105c5fb55898a5c3fd2141ac20a7a681889f71",
          "sha1": "b4b6fd14c1a36f2e9bdcf5196ae82eb29fc7730b",
          "md5": "270a47216a3548b5d53ea0188b83af6c"
        }
      ]
    }
  ]
}
