{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.10.0.aar",
          "url": "livebuy-reference-ui-4.10.0.aar",
          "size": 2780151,
          "sha512": "80a3f30b3e619762b6114a6c27c4c4a7a621b4268b6be9104a06968e65102ddaee5d8b26b110573edd1de8d40d9c01f23e51bc1f9d1078c2e4a4f9a4bab27541",
          "sha256": "1ba0beee04fc46c60840a91e4ee105dd6a1c59baeb328a3a0a875edb21350e97",
          "sha1": "af5b95ce6e59d3094b11dd10f93e37ab3082f773",
          "md5": "ff3036a3f1c8c00a755ee49a856d109c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.10.0.aar",
          "url": "livebuy-reference-ui-4.10.0.aar",
          "size": 2780151,
          "sha512": "80a3f30b3e619762b6114a6c27c4c4a7a621b4268b6be9104a06968e65102ddaee5d8b26b110573edd1de8d40d9c01f23e51bc1f9d1078c2e4a4f9a4bab27541",
          "sha256": "1ba0beee04fc46c60840a91e4ee105dd6a1c59baeb328a3a0a875edb21350e97",
          "sha1": "af5b95ce6e59d3094b11dd10f93e37ab3082f773",
          "md5": "ff3036a3f1c8c00a755ee49a856d109c"
        }
      ]
    }
  ]
}
