{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-ui",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy",
          "version": {
            "requires": "4.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-ui-4.20.0.aar",
          "url": "livebuy-ui-4.20.0.aar",
          "size": 264779,
          "sha512": "ff265b5ae1e5f533e7ccde21310bee41c8910c4a968b469f379ce683599690c267e64357c7f1735aa295b4c16468e322159c082abcaec0976dc262a112a62ec6",
          "sha256": "225af98fa4a4b70b9a7ef43ce6a61fae1f9bc3777eaef720e862978c9056a31a",
          "sha1": "d4c944eca35198843f8511e7dd84458a536f1e31",
          "md5": "99784f02711033097464c8a9aa3066ad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy",
          "version": {
            "requires": "4.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-ui-4.20.0.aar",
          "url": "livebuy-ui-4.20.0.aar",
          "size": 264779,
          "sha512": "ff265b5ae1e5f533e7ccde21310bee41c8910c4a968b469f379ce683599690c267e64357c7f1735aa295b4c16468e322159c082abcaec0976dc262a112a62ec6",
          "sha256": "225af98fa4a4b70b9a7ef43ce6a61fae1f9bc3777eaef720e862978c9056a31a",
          "sha1": "d4c944eca35198843f8511e7dd84458a536f1e31",
          "md5": "99784f02711033097464c8a9aa3066ad"
        }
      ]
    }
  ]
}
