{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.20.0.aar",
          "url": "livebuy-reference-ui-4.20.0.aar",
          "size": 3261827,
          "sha512": "1fe95504f622544880e6841761244b7f6d4b9d650f87db9ee243acdcfce3ded23a20b641b7edec7b4c0b34d4d2a858d78a265c86b05b3e929437c888b0b0bf5c",
          "sha256": "26f9bce67b8792212a30630d028af5c70dc238d50181f9d2f2b3612b7061227d",
          "sha1": "d8cdb2fa75127cf9841d08c842dcc4d065104cab",
          "md5": "0e36bbf3981188cae6b3531614642d46"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.20.0.aar",
          "url": "livebuy-reference-ui-4.20.0.aar",
          "size": 3261827,
          "sha512": "1fe95504f622544880e6841761244b7f6d4b9d650f87db9ee243acdcfce3ded23a20b641b7edec7b4c0b34d4d2a858d78a265c86b05b3e929437c888b0b0bf5c",
          "sha256": "26f9bce67b8792212a30630d028af5c70dc238d50181f9d2f2b3612b7061227d",
          "sha1": "d8cdb2fa75127cf9841d08c842dcc4d065104cab",
          "md5": "0e36bbf3981188cae6b3531614642d46"
        }
      ]
    }
  ]
}
