{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.4.0.aar",
          "url": "livebuy-reference-ui-4.4.0.aar",
          "size": 2571377,
          "sha512": "8520a5abfca83f4e05b489cce6f55e0c990550d60e8a2e24be861cd5c7586c7d160b12d8630ae7ee6d7a7a5ecd7e6afcda9b41f2e602cd5ba8eb6c9ee11f5134",
          "sha256": "16e96507b41dd4ca4538cee3e578dbf67d70b15b8c46f4b264d688e3d218d671",
          "sha1": "3978038b018fa9f9ad544beb787c4584a3d0e36b",
          "md5": "c0f354d60c659ea3f8fd101d03e4903e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.4.0.aar",
          "url": "livebuy-reference-ui-4.4.0.aar",
          "size": 2571377,
          "sha512": "8520a5abfca83f4e05b489cce6f55e0c990550d60e8a2e24be861cd5c7586c7d160b12d8630ae7ee6d7a7a5ecd7e6afcda9b41f2e602cd5ba8eb6c9ee11f5134",
          "sha256": "16e96507b41dd4ca4538cee3e578dbf67d70b15b8c46f4b264d688e3d218d671",
          "sha1": "3978038b018fa9f9ad544beb787c4584a3d0e36b",
          "md5": "c0f354d60c659ea3f8fd101d03e4903e"
        }
      ]
    }
  ]
}
