{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.26.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.26.2.aar",
          "url": "livebuy-reference-ui-4.26.2.aar",
          "size": 3378961,
          "sha512": "19bce35178f3fb51d5b2d158aac0e8dd5a267fedf0c75a56b839353f00762ec0dab84ace96fff14954b933dd9740a2b5fcbd34e0dd4e7ea955a155c3544f822a",
          "sha256": "e49b8a8fb921aeb7af5da78af8d3082cee8b093bf1e2ea59836fbdf19e723678",
          "sha1": "2868f93675b178feefb9949b42020cbbdc0a2fc7",
          "md5": "ba9c17b9a18482c6aabf3e3b65245238"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.26.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.26.2.aar",
          "url": "livebuy-reference-ui-4.26.2.aar",
          "size": 3378961,
          "sha512": "19bce35178f3fb51d5b2d158aac0e8dd5a267fedf0c75a56b839353f00762ec0dab84ace96fff14954b933dd9740a2b5fcbd34e0dd4e7ea955a155c3544f822a",
          "sha256": "e49b8a8fb921aeb7af5da78af8d3082cee8b093bf1e2ea59836fbdf19e723678",
          "sha1": "2868f93675b178feefb9949b42020cbbdc0a2fc7",
          "md5": "ba9c17b9a18482c6aabf3e3b65245238"
        }
      ]
    }
  ]
}
