{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.9.0.aar",
          "url": "livebuy-reference-ui-4.9.0.aar",
          "size": 2768799,
          "sha512": "e2ff9e1f42248b4da5ace2dd552b6fb498d6ad755e783bca13597134f8be82686246f6510fc8b5757a8dcc5d7654682056e6843e53f75ad372b92719a3097c89",
          "sha256": "ca1e60f0d1cf0a5eb519f4949e6e09ff8a1ca4e570a73d1cf058cbfdd16a96de",
          "sha1": "effd00189791e372b536708f44532404325a3bc2",
          "md5": "05b0f591f71c4a7f92cec06ac8c44704"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.9.0.aar",
          "url": "livebuy-reference-ui-4.9.0.aar",
          "size": 2768799,
          "sha512": "e2ff9e1f42248b4da5ace2dd552b6fb498d6ad755e783bca13597134f8be82686246f6510fc8b5757a8dcc5d7654682056e6843e53f75ad372b92719a3097c89",
          "sha256": "ca1e60f0d1cf0a5eb519f4949e6e09ff8a1ca4e570a73d1cf058cbfdd16a96de",
          "sha1": "effd00189791e372b536708f44532404325a3bc2",
          "md5": "05b0f591f71c4a7f92cec06ac8c44704"
        }
      ]
    }
  ]
}
