{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.6.0.aar",
          "url": "livebuy-reference-ui-4.6.0.aar",
          "size": 2624040,
          "sha512": "1cd77426d801765f101ee3ae4d8dfcfade17e15ea78ed07ddd1d8409288b07fab6b1ece459ac72c60f36b044533981995d80a4ad62f0c6fdbcbfc16ba98bd2f7",
          "sha256": "e82fc8bc9bdd949115044ffcbf9f4ddf19dd09565687a65e2c7619ad214860ec",
          "sha1": "c8fe99843d7ad58fd594499f59bc029ef9f46569",
          "md5": "f5b4df4e5f2956a87c4655ac96ba9505"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.6.0.aar",
          "url": "livebuy-reference-ui-4.6.0.aar",
          "size": 2624040,
          "sha512": "1cd77426d801765f101ee3ae4d8dfcfade17e15ea78ed07ddd1d8409288b07fab6b1ece459ac72c60f36b044533981995d80a4ad62f0c6fdbcbfc16ba98bd2f7",
          "sha256": "e82fc8bc9bdd949115044ffcbf9f4ddf19dd09565687a65e2c7619ad214860ec",
          "sha1": "c8fe99843d7ad58fd594499f59bc029ef9f46569",
          "md5": "f5b4df4e5f2956a87c4655ac96ba9505"
        }
      ]
    }
  ]
}
