{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.11.0.aar",
          "url": "livebuy-reference-ui-4.11.0.aar",
          "size": 2942672,
          "sha512": "8875cc36844aef57da9b20dc0f210251770a31cb00c7b16a1fbd099346fc4b67b2d80ce27923838d64b69011e3fb107964f2e56227e7d644911b87398b3ec817",
          "sha256": "48da416638b06c4a73dc8112f5466fcf15ee87bd81e618cd8a4d6106a8de999b",
          "sha1": "71623ca2f9d5905ebceecb52ef507aab43fe08e1",
          "md5": "1f82e4d6045d613d57d6354314c0cad9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.11.0.aar",
          "url": "livebuy-reference-ui-4.11.0.aar",
          "size": 2942672,
          "sha512": "8875cc36844aef57da9b20dc0f210251770a31cb00c7b16a1fbd099346fc4b67b2d80ce27923838d64b69011e3fb107964f2e56227e7d644911b87398b3ec817",
          "sha256": "48da416638b06c4a73dc8112f5466fcf15ee87bd81e618cd8a4d6106a8de999b",
          "sha1": "71623ca2f9d5905ebceecb52ef507aab43fe08e1",
          "md5": "1f82e4d6045d613d57d6354314c0cad9"
        }
      ]
    }
  ]
}
