{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.22.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.22.0.aar",
          "url": "livebuy-reference-ui-4.22.0.aar",
          "size": 3312397,
          "sha512": "e86047f68ae1600f9a3edc489ff59f0510baedf024a6925293140c902fc12c1a9245115b1dea9b1c04df52e586c7056aab6e060f8e9e385a3e028460e3f49293",
          "sha256": "d8541429bdd8bfb050240873ed3511e8db272ed69e65aa5ce8be806bc78843f5",
          "sha1": "ff1957de6f11bac07a6d29fadb40e671c2eb024f",
          "md5": "a6098ce8aeba9807357796ab99f4ac0b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.22.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.22.0.aar",
          "url": "livebuy-reference-ui-4.22.0.aar",
          "size": 3312397,
          "sha512": "e86047f68ae1600f9a3edc489ff59f0510baedf024a6925293140c902fc12c1a9245115b1dea9b1c04df52e586c7056aab6e060f8e9e385a3e028460e3f49293",
          "sha256": "d8541429bdd8bfb050240873ed3511e8db272ed69e65aa5ce8be806bc78843f5",
          "sha1": "ff1957de6f11bac07a6d29fadb40e671c2eb024f",
          "md5": "a6098ce8aeba9807357796ab99f4ac0b"
        }
      ]
    }
  ]
}
