{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.17.0.aar",
          "url": "livebuy-reference-ui-4.17.0.aar",
          "size": 3201075,
          "sha512": "703f399837c553ad4c0e4ca4d94c8cf138630fd4c6f6e6f7e62ed850e909fa52533672b8ba27616400f3589bf4a8987ab7bfcea315ac0df75567a0726a6c484f",
          "sha256": "ff976686fa9be92a2d69a732e10cf4d947438c6f1177289f72fb43f9a77c612d",
          "sha1": "4b8b9cb5d9fc6468bfdebc0b74ecc0101c119fd1",
          "md5": "014214d65780d91312deedaf2167a797"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.17.0.aar",
          "url": "livebuy-reference-ui-4.17.0.aar",
          "size": 3201075,
          "sha512": "703f399837c553ad4c0e4ca4d94c8cf138630fd4c6f6e6f7e62ed850e909fa52533672b8ba27616400f3589bf4a8987ab7bfcea315ac0df75567a0726a6c484f",
          "sha256": "ff976686fa9be92a2d69a732e10cf4d947438c6f1177289f72fb43f9a77c612d",
          "sha1": "4b8b9cb5d9fc6468bfdebc0b74ecc0101c119fd1",
          "md5": "014214d65780d91312deedaf2167a797"
        }
      ]
    }
  ]
}
