{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.2.0.aar",
          "url": "livebuy-reference-ui-4.2.0.aar",
          "size": 2410124,
          "sha512": "965e38649c24a8d9f6e79f597fa90663cfbbcbaa9dcd85b7293b65727bd48a5074db510b9b914040789a4ae7b520dcc6c047fbb9795a2769e5a5aee4d037896c",
          "sha256": "5c0945a4478639b92bf177ad3918b15ebeb424f3af3ffd390cc9e0969cfa1c0e",
          "sha1": "8846595950cb2d0313e1601c484702682fdfe68e",
          "md5": "473a11ef045dfa85a448539f77feaed2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.2.0.aar",
          "url": "livebuy-reference-ui-4.2.0.aar",
          "size": 2410124,
          "sha512": "965e38649c24a8d9f6e79f597fa90663cfbbcbaa9dcd85b7293b65727bd48a5074db510b9b914040789a4ae7b520dcc6c047fbb9795a2769e5a5aee4d037896c",
          "sha256": "5c0945a4478639b92bf177ad3918b15ebeb424f3af3ffd390cc9e0969cfa1c0e",
          "sha1": "8846595950cb2d0313e1601c484702682fdfe68e",
          "md5": "473a11ef045dfa85a448539f77feaed2"
        }
      ]
    }
  ]
}
