{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.7.0.aar",
          "url": "livebuy-reference-ui-4.7.0.aar",
          "size": 2718936,
          "sha512": "2440e05501cf1d21a5a304bbe9cf7d65c2661e53b0d12eed252d7c9d1a064496944ea001b1f8cbcb7421bd9ff7146b2ef194a492f8332d0737324c52c1afb390",
          "sha256": "ecd6f89255e8fd0d8176060a498fabaa7baa0630c24de774191a4d972c248caf",
          "sha1": "4d54d0d8359c8655e1c228e7dd1f3e4cf0383f60",
          "md5": "b02bf2d941da497dcdf3f7eef8a180fc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.7.0.aar",
          "url": "livebuy-reference-ui-4.7.0.aar",
          "size": 2718936,
          "sha512": "2440e05501cf1d21a5a304bbe9cf7d65c2661e53b0d12eed252d7c9d1a064496944ea001b1f8cbcb7421bd9ff7146b2ef194a492f8332d0737324c52c1afb390",
          "sha256": "ecd6f89255e8fd0d8176060a498fabaa7baa0630c24de774191a4d972c248caf",
          "sha1": "4d54d0d8359c8655e1c228e7dd1f3e4cf0383f60",
          "md5": "b02bf2d941da497dcdf3f7eef8a180fc"
        }
      ]
    }
  ]
}
