{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.13.0.aar",
          "url": "livebuy-reference-ui-4.13.0.aar",
          "size": 3012090,
          "sha512": "6cabffba50a4153d3e928a84540aeac65c8d6e945d4e5693834f2da9754a370eb2d91e6355090f4dfcdd8caa5783e82d51acb8abdaadbe8a33323aa80561dd4a",
          "sha256": "870bbfffb3d12f56b1bb13871492af97c6bae45f922fe1dfa598b5fab86cb5fe",
          "sha1": "d1d30b0cbd41dc57dd7fd316b887ace3a859646b",
          "md5": "d275da120f27bcf3a4a5c32661f1ecc6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.13.0.aar",
          "url": "livebuy-reference-ui-4.13.0.aar",
          "size": 3012090,
          "sha512": "6cabffba50a4153d3e928a84540aeac65c8d6e945d4e5693834f2da9754a370eb2d91e6355090f4dfcdd8caa5783e82d51acb8abdaadbe8a33323aa80561dd4a",
          "sha256": "870bbfffb3d12f56b1bb13871492af97c6bae45f922fe1dfa598b5fab86cb5fe",
          "sha1": "d1d30b0cbd41dc57dd7fd316b887ace3a859646b",
          "md5": "d275da120f27bcf3a4a5c32661f1ecc6"
        }
      ]
    }
  ]
}
