{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.3.0.aar",
          "url": "livebuy-reference-ui-4.3.0.aar",
          "size": 2517348,
          "sha512": "18006cf224698b692b618cd9dc84f0e5afc6bf3b88f1bbb8399ea7e6868eb9e1f58ae3c6d95775a612faf15e68575784a8b4ece66c020f25aeaa794275519d3c",
          "sha256": "6bb8f2f66c0da29d63133ce32ec336d279e6daab59dc3e94ce34960bc3c0b810",
          "sha1": "4e7fa6a00c4afbb5bd9a0fc45bfc14302c4a664b",
          "md5": "7cc698305a32a060b0889a356bbe53b5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.3.0.aar",
          "url": "livebuy-reference-ui-4.3.0.aar",
          "size": 2517348,
          "sha512": "18006cf224698b692b618cd9dc84f0e5afc6bf3b88f1bbb8399ea7e6868eb9e1f58ae3c6d95775a612faf15e68575784a8b4ece66c020f25aeaa794275519d3c",
          "sha256": "6bb8f2f66c0da29d63133ce32ec336d279e6daab59dc3e94ce34960bc3c0b810",
          "sha1": "4e7fa6a00c4afbb5bd9a0fc45bfc14302c4a664b",
          "md5": "7cc698305a32a060b0889a356bbe53b5"
        }
      ]
    }
  ]
}
