{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.19.0.aar",
          "url": "livebuy-reference-ui-4.19.0.aar",
          "size": 3243413,
          "sha512": "66d1f6d74d7bff3b4642e080e3533ecc1412062271e6d6062a25b154530b7bec27d5abacd3a312479b91ea81036d52223c49289bbc8762322c2a00ba0499e05a",
          "sha256": "b14adade9f42793961b09d52a42aeb2cc10d1ce00e83c7423232a15fcdf26dc8",
          "sha1": "dcafd320dfaf1e0c3806d068f942626610eb8f61",
          "md5": "f2e57d1b4ce1128dc0de7af311f6e75f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.19.0.aar",
          "url": "livebuy-reference-ui-4.19.0.aar",
          "size": 3243413,
          "sha512": "66d1f6d74d7bff3b4642e080e3533ecc1412062271e6d6062a25b154530b7bec27d5abacd3a312479b91ea81036d52223c49289bbc8762322c2a00ba0499e05a",
          "sha256": "b14adade9f42793961b09d52a42aeb2cc10d1ce00e83c7423232a15fcdf26dc8",
          "sha1": "dcafd320dfaf1e0c3806d068f942626610eb8f61",
          "md5": "f2e57d1b4ce1128dc0de7af311f6e75f"
        }
      ]
    }
  ]
}
