{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-ui",
    "version": "4.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-ui-4.24.0.aar",
          "url": "livebuy-ui-4.24.0.aar",
          "size": 267978,
          "sha512": "70d430ca1171e28d2b8907ae939522ab6f3bae1d7773e78efce10099dd0e366608eb241f9310620311ad379d818c43a5409a867df64ea65eeb5ae5297f1e2235",
          "sha256": "c053ed575feabdb465118b4c158768553891f90fcd2773a11b9e8f63a365a774",
          "sha1": "ae910cc8178f99e31795315816a261517f16bf30",
          "md5": "9e95260ad3d1a4b90e0d41ba10b0ed82"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-ui-4.24.0.aar",
          "url": "livebuy-ui-4.24.0.aar",
          "size": 267978,
          "sha512": "70d430ca1171e28d2b8907ae939522ab6f3bae1d7773e78efce10099dd0e366608eb241f9310620311ad379d818c43a5409a867df64ea65eeb5ae5297f1e2235",
          "sha256": "c053ed575feabdb465118b4c158768553891f90fcd2773a11b9e8f63a365a774",
          "sha1": "ae910cc8178f99e31795315816a261517f16bf30",
          "md5": "9e95260ad3d1a4b90e0d41ba10b0ed82"
        }
      ]
    }
  ]
}
