{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-3.2.0.aar",
          "url": "livebuy-reference-ui-3.2.0.aar",
          "size": 2377807,
          "sha512": "5c139ff9cfe60a39c8e7552f1bf09c7cb1642e9b892839fcaabfa82488304cce8d2c6da41f75fe5276ebe7ea12a18a3c7614c4b12157060c23450ffcb6a1c65b",
          "sha256": "2206e0c0803ce8c178285741b0543efb95000424c68c2aafc3ee10214f73602d",
          "sha1": "3455b9c1f7241e535ffdc9b4ef1240d1722f8299",
          "md5": "c6c00ea98486cbc3400136b8e318447e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-3.2.0.aar",
          "url": "livebuy-reference-ui-3.2.0.aar",
          "size": 2377807,
          "sha512": "5c139ff9cfe60a39c8e7552f1bf09c7cb1642e9b892839fcaabfa82488304cce8d2c6da41f75fe5276ebe7ea12a18a3c7614c4b12157060c23450ffcb6a1c65b",
          "sha256": "2206e0c0803ce8c178285741b0543efb95000424c68c2aafc3ee10214f73602d",
          "sha1": "3455b9c1f7241e535ffdc9b4ef1240d1722f8299",
          "md5": "c6c00ea98486cbc3400136b8e318447e"
        }
      ]
    }
  ]
}
