{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.21.0.aar",
          "url": "livebuy-reference-ui-4.21.0.aar",
          "size": 3288410,
          "sha512": "6747314b3f8cd0b993e45d959bb2068cfb586da71c253e184dc295483c004510fab6f8f9cdf014a493d2d10e7a1a2fd81563287bd3b05eeb8feff76a55402c3e",
          "sha256": "91e4ecefffa52d34945e935ad3899452127e20ff8972f9efc64ac7d24c6954a1",
          "sha1": "80ecc1fedfcea3c014860d56392575c2f2718100",
          "md5": "14332fb7607ba0a70ed800dd6048f201"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.21.0.aar",
          "url": "livebuy-reference-ui-4.21.0.aar",
          "size": 3288410,
          "sha512": "6747314b3f8cd0b993e45d959bb2068cfb586da71c253e184dc295483c004510fab6f8f9cdf014a493d2d10e7a1a2fd81563287bd3b05eeb8feff76a55402c3e",
          "sha256": "91e4ecefffa52d34945e935ad3899452127e20ff8972f9efc64ac7d24c6954a1",
          "sha1": "80ecc1fedfcea3c014860d56392575c2f2718100",
          "md5": "14332fb7607ba0a70ed800dd6048f201"
        }
      ]
    }
  ]
}
