{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.14.0.aar",
          "url": "livebuy-reference-ui-4.14.0.aar",
          "size": 3112021,
          "sha512": "3c4d2bf1dad917b09e67db72f9c693f22a9ead684ba9ad6a8fb67a1871a2903292898d866f03942982ecdf0f61c104922724dca95c98867bf3e17308a33de31e",
          "sha256": "91cc1644659bd4b446387460bd6bac23db189d8e9c3bb4bf2bbe3322ed0b7a93",
          "sha1": "742299f38125180d0bb7a950ffb014189d3d5a2e",
          "md5": "d311176ad61f7f4afc4f3e1382a70085"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.14.0.aar",
          "url": "livebuy-reference-ui-4.14.0.aar",
          "size": 3112021,
          "sha512": "3c4d2bf1dad917b09e67db72f9c693f22a9ead684ba9ad6a8fb67a1871a2903292898d866f03942982ecdf0f61c104922724dca95c98867bf3e17308a33de31e",
          "sha256": "91cc1644659bd4b446387460bd6bac23db189d8e9c3bb4bf2bbe3322ed0b7a93",
          "sha1": "742299f38125180d0bb7a950ffb014189d3d5a2e",
          "md5": "d311176ad61f7f4afc4f3e1382a70085"
        }
      ]
    }
  ]
}
