{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-4.0.0.aar",
          "url": "livebuy-4.0.0.aar",
          "size": 821293,
          "sha512": "097dbb7b3e7aa622e28c09b926b6d9a544f057e6050ba5284861526ec6d6caf69b2d4c0cf4a0a430ed4754175fc670e805c26c3a174a5fca385666bc5967c91b",
          "sha256": "3ff2bf45dead0ea953a4b64b7d5f896c9e272293a3e37b932399a5e5e9d1d5ec",
          "sha1": "84d0bcfa44ea1878fecd0b9356eaad984d0609fe",
          "md5": "f4b9e4c459b3f00960ffd7c0cb4b180a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-session",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "ivs-player",
          "version": {
            "requires": "1.52.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-4.0.0.aar",
          "url": "livebuy-4.0.0.aar",
          "size": 821293,
          "sha512": "097dbb7b3e7aa622e28c09b926b6d9a544f057e6050ba5284861526ec6d6caf69b2d4c0cf4a0a430ed4754175fc670e805c26c3a174a5fca385666bc5967c91b",
          "sha256": "3ff2bf45dead0ea953a4b64b7d5f896c9e272293a3e37b932399a5e5e9d1d5ec",
          "sha1": "84d0bcfa44ea1878fecd0b9356eaad984d0609fe",
          "md5": "f4b9e4c459b3f00960ffd7c0cb4b180a"
        }
      ]
    }
  ]
}
