{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.21.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.21.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.21.2.aar",
          "url": "livebuy-reference-ui-4.21.2.aar",
          "size": 3292024,
          "sha512": "aadf3fc322dcee88008948883a2a8af7c1c6bc5121fe6e26477c578d3f5cf90821a9dcf41d325984126ad4ac72af610117aac96d2670321bc5444fefdb5768e2",
          "sha256": "153937d7a306946bc05ae2e606ec8c1cc80feb14dea1a5d95cb5d0d3f489d1a4",
          "sha1": "4010877d812bacfa6271e11fdd540c95f194be53",
          "md5": "550382ba3a75c620c1d53acbe38ef639"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.21.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.21.2.aar",
          "url": "livebuy-reference-ui-4.21.2.aar",
          "size": 3292024,
          "sha512": "aadf3fc322dcee88008948883a2a8af7c1c6bc5121fe6e26477c578d3f5cf90821a9dcf41d325984126ad4ac72af610117aac96d2670321bc5444fefdb5768e2",
          "sha256": "153937d7a306946bc05ae2e606ec8c1cc80feb14dea1a5d95cb5d0d3f489d1a4",
          "sha1": "4010877d812bacfa6271e11fdd540c95f194be53",
          "md5": "550382ba3a75c620c1d53acbe38ef639"
        }
      ]
    }
  ]
}
