{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy",
    "version": "4.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-4.13.1.aar",
          "url": "livebuy-4.13.1.aar",
          "size": 864425,
          "sha512": "8b5fcc2458573c28586c222a2f3e561fe6431c87e9bb5ad9bb784d9603f094bb375631ae51db87dba5e2e55c36ef8f6370fd0ba47ab191d4cb1477e3efb095c4",
          "sha256": "a4bf6e2d75913bdfdb2dd36db93d863cbbc63f5c03ff45c573d0cc290174fa5c",
          "sha1": "ec569a463f5114a02d455d2f16ad4fcd74527dcd",
          "md5": "cb600e8eb6baeb5dbda9627337c6bcbc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-session",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "ivs-player",
          "version": {
            "requires": "1.52.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-4.13.1.aar",
          "url": "livebuy-4.13.1.aar",
          "size": 864425,
          "sha512": "8b5fcc2458573c28586c222a2f3e561fe6431c87e9bb5ad9bb784d9603f094bb375631ae51db87dba5e2e55c36ef8f6370fd0ba47ab191d4cb1477e3efb095c4",
          "sha256": "a4bf6e2d75913bdfdb2dd36db93d863cbbc63f5c03ff45c573d0cc290174fa5c",
          "sha1": "ec569a463f5114a02d455d2f16ad4fcd74527dcd",
          "md5": "cb600e8eb6baeb5dbda9627337c6bcbc"
        }
      ]
    }
  ]
}
