{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.24.0.aar",
          "url": "livebuy-reference-ui-4.24.0.aar",
          "size": 3324717,
          "sha512": "72c6c9dfd1f9b442c155943ba77f2496f3c277630d392d6fcb7ab354dc14ee91c88405b7ec1528ac0e1ef8854e3ef5a0d232bd76c7b30d24856fbb0c76a7b971",
          "sha256": "2ca66f888f9b70c9223c237b2ee4ec5b12d1bbc08ad9906aaa8a245fa133a501",
          "sha1": "f59fc5c5cd3587d070dce3cfc68a3291ba95728d",
          "md5": "171bbf4b46d33acdb205647ac64e73e4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.24.0.aar",
          "url": "livebuy-reference-ui-4.24.0.aar",
          "size": 3324717,
          "sha512": "72c6c9dfd1f9b442c155943ba77f2496f3c277630d392d6fcb7ab354dc14ee91c88405b7ec1528ac0e1ef8854e3ef5a0d232bd76c7b30d24856fbb0c76a7b971",
          "sha256": "2ca66f888f9b70c9223c237b2ee4ec5b12d1bbc08ad9906aaa8a245fa133a501",
          "sha1": "f59fc5c5cd3587d070dce3cfc68a3291ba95728d",
          "md5": "171bbf4b46d33acdb205647ac64e73e4"
        }
      ]
    }
  ]
}
