{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.0.0.aar",
          "url": "livebuy-reference-ui-4.0.0.aar",
          "size": 2392509,
          "sha512": "8511118cd5c7583ac28e58326fee64d5abe0a6a3c33db5b2da29c01d47a03b1cf06ac006a711800af9e4659b9ebbf40dd3e662545133befe55728d6fa9f3cf67",
          "sha256": "2e8abfb371ece5de979a3ac8cbcdc912e5b4f220b2a086887900529405a15489",
          "sha1": "f0eaec2a339e34e419696bc7aaae170db2678f54",
          "md5": "d8fab15bb1d314c10a697e56c1fab3d3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.0.0.aar",
          "url": "livebuy-reference-ui-4.0.0.aar",
          "size": 2392509,
          "sha512": "8511118cd5c7583ac28e58326fee64d5abe0a6a3c33db5b2da29c01d47a03b1cf06ac006a711800af9e4659b9ebbf40dd3e662545133befe55728d6fa9f3cf67",
          "sha256": "2e8abfb371ece5de979a3ac8cbcdc912e5b4f220b2a086887900529405a15489",
          "sha1": "f0eaec2a339e34e419696bc7aaae170db2678f54",
          "md5": "d8fab15bb1d314c10a697e56c1fab3d3"
        }
      ]
    }
  ]
}
