{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-ui",
    "version": "4.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-ui-4.25.0.aar",
          "url": "livebuy-ui-4.25.0.aar",
          "size": 272134,
          "sha512": "2a3cf9d0202a9b87cfb99ceb59e7b77389199d94babdc0d80da4824ff2e7bba3d6544b37f32e3071709d658195cdb6f26a76fe01963acd778c4bbb79d6eedc71",
          "sha256": "4daae065639b0dbb07a6c81ca9a9b8042206e21117b438591c3b570f0425d5c3",
          "sha1": "4271a0399435c4efdaf310d5003669fa8c8ef942",
          "md5": "730fb5bb59771670a7eb507db74a521e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-ui-4.25.0.aar",
          "url": "livebuy-ui-4.25.0.aar",
          "size": 272134,
          "sha512": "2a3cf9d0202a9b87cfb99ceb59e7b77389199d94babdc0d80da4824ff2e7bba3d6544b37f32e3071709d658195cdb6f26a76fe01963acd778c4bbb79d6eedc71",
          "sha256": "4daae065639b0dbb07a6c81ca9a9b8042206e21117b438591c3b570f0425d5c3",
          "sha1": "4271a0399435c4efdaf310d5003669fa8c8ef942",
          "md5": "730fb5bb59771670a7eb507db74a521e"
        }
      ]
    }
  ]
}
