{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy",
    "version": "4.21.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-4.21.2.aar",
          "url": "livebuy-4.21.2.aar",
          "size": 878572,
          "sha512": "725e55c69f3d1cee1ad093409b91a0cf17ae0c2cd8067988f340a3c305a5f348c8ad7f866bcfc15eab513e793e1a3cd53a3ea423ab1c7e523684f8ca10a31a43",
          "sha256": "e7af7c6816d5b6c2c7b6bb61127459dfcdc37b8f7d623af3ec1353d0527d84b5",
          "sha1": "ac057ef26192ed92e8b7155d5480c4ea1a96884f",
          "md5": "c4eb0542b29a80bbc0d241d9da1afaa4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-session",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "ivs-player",
          "version": {
            "requires": "1.52.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-4.21.2.aar",
          "url": "livebuy-4.21.2.aar",
          "size": 878572,
          "sha512": "725e55c69f3d1cee1ad093409b91a0cf17ae0c2cd8067988f340a3c305a5f348c8ad7f866bcfc15eab513e793e1a3cd53a3ea423ab1c7e523684f8ca10a31a43",
          "sha256": "e7af7c6816d5b6c2c7b6bb61127459dfcdc37b8f7d623af3ec1353d0527d84b5",
          "sha1": "ac057ef26192ed92e8b7155d5480c4ea1a96884f",
          "md5": "c4eb0542b29a80bbc0d241d9da1afaa4"
        }
      ]
    }
  ]
}
