{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy",
    "version": "4.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-4.23.0.aar",
          "url": "livebuy-4.23.0.aar",
          "size": 885369,
          "sha512": "8ff1cad4aec0f7a7f74bdf37384c0f294519d57d000c3f57870c37a11724b32282ed1d7ebc7623db71d85ff4d34f5875630bc74ad39e213dd05b29d134de3e77",
          "sha256": "f025d8a87ad3fe86f10323085511591e7c7755ec7619476705380dd049b91ff5",
          "sha1": "043589bd91ac37d37f0225ea0cf5e9272c8c63ac",
          "md5": "eaa1ef23c4a4510f719ec6b7b09c5469"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-session",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "ivs-player",
          "version": {
            "requires": "1.52.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-4.23.0.aar",
          "url": "livebuy-4.23.0.aar",
          "size": 885369,
          "sha512": "8ff1cad4aec0f7a7f74bdf37384c0f294519d57d000c3f57870c37a11724b32282ed1d7ebc7623db71d85ff4d34f5875630bc74ad39e213dd05b29d134de3e77",
          "sha256": "f025d8a87ad3fe86f10323085511591e7c7755ec7619476705380dd049b91ff5",
          "sha1": "043589bd91ac37d37f0225ea0cf5e9272c8c63ac",
          "md5": "eaa1ef23c4a4510f719ec6b7b09c5469"
        }
      ]
    }
  ]
}
