{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.26.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.26.0.aar",
          "url": "livebuy-reference-ui-4.26.0.aar",
          "size": 3375503,
          "sha512": "7c52b2683aa431c6fc293f6f546c545da325cb37fbd07b115ed4713b0ebfac97b262aa76d2b7ecf0e2cc15a584e305f66da6adc3e7f52ac04bb5250aad215113",
          "sha256": "1f0f9432a1d1bb25df77a1cb1b24ed28c49b7da89a69132274183ee5b4bf11f0",
          "sha1": "6d0dabc1494d7bf0dbf831d12f571ecffe867141",
          "md5": "386f1460f4eb3cce19fd8ed17f8aa822"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.26.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.26.0.aar",
          "url": "livebuy-reference-ui-4.26.0.aar",
          "size": 3375503,
          "sha512": "7c52b2683aa431c6fc293f6f546c545da325cb37fbd07b115ed4713b0ebfac97b262aa76d2b7ecf0e2cc15a584e305f66da6adc3e7f52ac04bb5250aad215113",
          "sha256": "1f0f9432a1d1bb25df77a1cb1b24ed28c49b7da89a69132274183ee5b4bf11f0",
          "sha1": "6d0dabc1494d7bf0dbf831d12f571ecffe867141",
          "md5": "386f1460f4eb3cce19fd8ed17f8aa822"
        }
      ]
    }
  ]
}
