{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.6.2.aar",
          "url": "livebuy-reference-ui-4.6.2.aar",
          "size": 2644744,
          "sha512": "a7cf810f8d00cc2a9ee4779bd5ad63a0f8eaa6c984e81cacc165e3271c51d5b7d18bd62499004b7b4546201cac4656dd65deff5bf249e076b7d554fb0c482187",
          "sha256": "911fc956cb574ce77a8e139b38e0903118927ff236ad6377a47f197c2182c7bc",
          "sha1": "b61b0e624e340874d63d1afd05db1dfefff4a442",
          "md5": "fe6ab3b1cb641b022dee43918498986e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.6.2.aar",
          "url": "livebuy-reference-ui-4.6.2.aar",
          "size": 2644744,
          "sha512": "a7cf810f8d00cc2a9ee4779bd5ad63a0f8eaa6c984e81cacc165e3271c51d5b7d18bd62499004b7b4546201cac4656dd65deff5bf249e076b7d554fb0c482187",
          "sha256": "911fc956cb574ce77a8e139b38e0903118927ff236ad6377a47f197c2182c7bc",
          "sha1": "b61b0e624e340874d63d1afd05db1dfefff4a442",
          "md5": "fe6ab3b1cb641b022dee43918498986e"
        }
      ]
    }
  ]
}
