{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.25.0.aar",
          "url": "livebuy-reference-ui-4.25.0.aar",
          "size": 3324734,
          "sha512": "4fe3b3018c1771ea5f9b05cf1031bd2db74c9365581f0516c24bd082c06420acc58992c5ecfc357bd54ef764f2a8e47a333e0d405ec5a5420a488aa5dd8ee705",
          "sha256": "b9d2e0bc15daafc3fe028961e6b7b589e9597a4702542c4fea50653784418f60",
          "sha1": "3416b9a8635da76a60c8d6b6af50944fc72a47cd",
          "md5": "65888c8811e543418a63d4ea646567cc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.25.0.aar",
          "url": "livebuy-reference-ui-4.25.0.aar",
          "size": 3324734,
          "sha512": "4fe3b3018c1771ea5f9b05cf1031bd2db74c9365581f0516c24bd082c06420acc58992c5ecfc357bd54ef764f2a8e47a333e0d405ec5a5420a488aa5dd8ee705",
          "sha256": "b9d2e0bc15daafc3fe028961e6b7b589e9597a4702542c4fea50653784418f60",
          "sha1": "3416b9a8635da76a60c8d6b6af50944fc72a47cd",
          "md5": "65888c8811e543418a63d4ea646567cc"
        }
      ]
    }
  ]
}
