{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.25.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.25.1.aar",
          "url": "livebuy-reference-ui-4.25.1.aar",
          "size": 3331042,
          "sha512": "73b3041dd780f12954cb0774d50d35fcd80b9d2d00056105097033d2d84c425e35916ae4199ddd8738cbcc458d35d34108afea24150bbd4bef8dc7a4a28d79eb",
          "sha256": "81444d2a887c112ab90006ba6892747bedd362e0706ab5f1c526236a0a8e6e12",
          "sha1": "fe0d7ad549e011a108ad25d285e969adbc01d83b",
          "md5": "0e86ffe3475f97cab48f381155edebe3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.25.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.25.1.aar",
          "url": "livebuy-reference-ui-4.25.1.aar",
          "size": 3331042,
          "sha512": "73b3041dd780f12954cb0774d50d35fcd80b9d2d00056105097033d2d84c425e35916ae4199ddd8738cbcc458d35d34108afea24150bbd4bef8dc7a4a28d79eb",
          "sha256": "81444d2a887c112ab90006ba6892747bedd362e0706ab5f1c526236a0a8e6e12",
          "sha1": "fe0d7ad549e011a108ad25d285e969adbc01d83b",
          "md5": "0e86ffe3475f97cab48f381155edebe3"
        }
      ]
    }
  ]
}
