{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-ui",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-ui-4.13.0.aar",
          "url": "livebuy-ui-4.13.0.aar",
          "size": 255773,
          "sha512": "24802f02886206b92ff2d7ed7dd3518cd2706bb52967c7445dcb8295e499a5edea7b835c2c7bdb9c925fa60ceef160ced969611e9c8b5e5011d11020a082b6eb",
          "sha256": "b992134ffe3cb3baa22f1115895dd7b6a1845050e6a28e6c45bda6dba5a4dd95",
          "sha1": "e9b7c8ecab6126a6301bfa11ea304b1b475b7a96",
          "md5": "b2efc1ebf18fb099bd671c3277f9d99f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-ui-4.13.0.aar",
          "url": "livebuy-ui-4.13.0.aar",
          "size": 255773,
          "sha512": "24802f02886206b92ff2d7ed7dd3518cd2706bb52967c7445dcb8295e499a5edea7b835c2c7bdb9c925fa60ceef160ced969611e9c8b5e5011d11020a082b6eb",
          "sha256": "b992134ffe3cb3baa22f1115895dd7b6a1845050e6a28e6c45bda6dba5a4dd95",
          "sha1": "e9b7c8ecab6126a6301bfa11ea304b1b475b7a96",
          "md5": "b2efc1ebf18fb099bd671c3277f9d99f"
        }
      ]
    }
  ]
}
