{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.18.0.aar",
          "url": "livebuy-reference-ui-4.18.0.aar",
          "size": 3243397,
          "sha512": "1f38aee1312a3ad410ebc3ba38fbdad93f17ecaad664c4b2c78591e486917acb6d1d9b4eac2c1862cd053664acb954954625bba96dd33ca2e9e7d4325bcc3230",
          "sha256": "823b0e94d66c204cc47537731d473ddd842c85997f0e4d550e26f51a360ded03",
          "sha1": "4238cab8afcd585c5c96cc54b176aab086f8dd38",
          "md5": "883b445baf6ff6180d4f03ccddeefdfb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.18.0.aar",
          "url": "livebuy-reference-ui-4.18.0.aar",
          "size": 3243397,
          "sha512": "1f38aee1312a3ad410ebc3ba38fbdad93f17ecaad664c4b2c78591e486917acb6d1d9b4eac2c1862cd053664acb954954625bba96dd33ca2e9e7d4325bcc3230",
          "sha256": "823b0e94d66c204cc47537731d473ddd842c85997f0e4d550e26f51a360ded03",
          "sha1": "4238cab8afcd585c5c96cc54b176aab086f8dd38",
          "md5": "883b445baf6ff6180d4f03ccddeefdfb"
        }
      ]
    }
  ]
}
