{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.15.0.aar",
          "url": "livebuy-reference-ui-4.15.0.aar",
          "size": 3112857,
          "sha512": "47e0b9cced6975a1bcd9d8f4767ecdc48270cab762394207665a9919f06156fe0ccc98f75940cc9e0beaf405288a497d751a54e5311eb79bb6f701213837bf76",
          "sha256": "ebe1cb1402b0a6816456da496838e47dcc4e423e555abde469656ba8e4ac0f6c",
          "sha1": "ea82b6a575054e1ee37b7d2641e4690bca22ff5b",
          "md5": "58a528219c3b6b9e35d5d92f2151c02d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.15.0.aar",
          "url": "livebuy-reference-ui-4.15.0.aar",
          "size": 3112857,
          "sha512": "47e0b9cced6975a1bcd9d8f4767ecdc48270cab762394207665a9919f06156fe0ccc98f75940cc9e0beaf405288a497d751a54e5311eb79bb6f701213837bf76",
          "sha256": "ebe1cb1402b0a6816456da496838e47dcc4e423e555abde469656ba8e4ac0f6c",
          "sha1": "ea82b6a575054e1ee37b7d2641e4690bca22ff5b",
          "md5": "58a528219c3b6b9e35d5d92f2151c02d"
        }
      ]
    }
  ]
}
