{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.16.0.aar",
          "url": "livebuy-reference-ui-4.16.0.aar",
          "size": 3187497,
          "sha512": "f2b009e4be754ba96b49ce29020bf1f9374417bce4f3897c038e519460fc40352fba00b5dff632b9e387b1c1cc42cbb9020fda2ae3deb23db4e634831531ce0d",
          "sha256": "d055ad8f97f378b3a0c91916fcc45b6eb31fab55f9de67cc0a738d734f3f4017",
          "sha1": "465e4f8c6d69d3d1521572a1516896bb51fa7247",
          "md5": "97215d4092f1d1092a0af1973b96d99d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.16.0.aar",
          "url": "livebuy-reference-ui-4.16.0.aar",
          "size": 3187497,
          "sha512": "f2b009e4be754ba96b49ce29020bf1f9374417bce4f3897c038e519460fc40352fba00b5dff632b9e387b1c1cc42cbb9020fda2ae3deb23db4e634831531ce0d",
          "sha256": "d055ad8f97f378b3a0c91916fcc45b6eb31fab55f9de67cc0a738d734f3f4017",
          "sha1": "465e4f8c6d69d3d1521572a1516896bb51fa7247",
          "md5": "97215d4092f1d1092a0af1973b96d99d"
        }
      ]
    }
  ]
}
