{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-reference-ui",
    "version": "4.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.13.1.aar",
          "url": "livebuy-reference-ui-4.13.1.aar",
          "size": 3011770,
          "sha512": "92985eaa20f421652481c0dd01f52ffcddf5ca8f82d40246f36de39464b87d09b7bbbc55a69190fb6176c10eaf3493d7bafbe86465f1c11cb272380055576c25",
          "sha256": "231284f13b9cdc61d83344d1fc889dbebe91f80fccc166aea2503306c2989e1d",
          "sha1": "66cd0d32b13b36ef9ab3b7997738815741dbaa26",
          "md5": "f1aa72df908bd8c0359dc1d8fa50b456"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy-ui",
          "version": {
            "requires": "4.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-reference-ui-4.13.1.aar",
          "url": "livebuy-reference-ui-4.13.1.aar",
          "size": 3011770,
          "sha512": "92985eaa20f421652481c0dd01f52ffcddf5ca8f82d40246f36de39464b87d09b7bbbc55a69190fb6176c10eaf3493d7bafbe86465f1c11cb272380055576c25",
          "sha256": "231284f13b9cdc61d83344d1fc889dbebe91f80fccc166aea2503306c2989e1d",
          "sha1": "66cd0d32b13b36ef9ab3b7997738815741dbaa26",
          "md5": "f1aa72df908bd8c0359dc1d8fa50b456"
        }
      ]
    }
  ]
}
