{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy-ui",
    "version": "4.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tv.livebuy",
          "module": "livebuy",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-ui-4.6.2.aar",
          "url": "livebuy-ui-4.6.2.aar",
          "size": 233514,
          "sha512": "9fb7a952180c62d93245f033d4f38bb72fcad9be9e27d45f6a276b92768a901876fc623dd031dee4591db5c2c82d931e86d5af23b477d679f842bc49fc20b2fd",
          "sha256": "52471981eb7851891b770f22c046d46f5f23d2c732c9b13d6e4061a26ded2def",
          "sha1": "91d5932d3affd05b99077f0d694305ba44e5fe68",
          "md5": "c6342e49ce387fe3bd80d6e8313f82af"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "tv.livebuy",
          "module": "livebuy",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-ui-4.6.2.aar",
          "url": "livebuy-ui-4.6.2.aar",
          "size": 233514,
          "sha512": "9fb7a952180c62d93245f033d4f38bb72fcad9be9e27d45f6a276b92768a901876fc623dd031dee4591db5c2c82d931e86d5af23b477d679f842bc49fc20b2fd",
          "sha256": "52471981eb7851891b770f22c046d46f5f23d2c732c9b13d6e4061a26ded2def",
          "sha1": "91d5932d3affd05b99077f0d694305ba44e5fe68",
          "md5": "c6342e49ce387fe3bd80d6e8313f82af"
        }
      ]
    }
  ]
}
