{
  "formatVersion": "1.1",
  "component": {
    "group": "tv.livebuy",
    "module": "livebuy",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-4.3.0.aar",
          "url": "livebuy-4.3.0.aar",
          "size": 848438,
          "sha512": "e536cc6f471e095000020fdbdc8e6cbc5317a09987051736bd94a98cc390bb09bb63fd243acd5de7cf5078fd100a93953c7866d5c6b8ffbece243d2a955c2a6f",
          "sha256": "3b5c90afb2ea8e8cc44cdec8e229352c806521c054dae6f4df28b99ba7f992d2",
          "sha1": "d5974a0c298f6e68375a38b82b70b8a9d23c74b7",
          "md5": "46b505c930adc4e2e1782f68a410d955"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-session",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "ivs-player",
          "version": {
            "requires": "1.52.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "livebuy-4.3.0.aar",
          "url": "livebuy-4.3.0.aar",
          "size": 848438,
          "sha512": "e536cc6f471e095000020fdbdc8e6cbc5317a09987051736bd94a98cc390bb09bb63fd243acd5de7cf5078fd100a93953c7866d5c6b8ffbece243d2a955c2a6f",
          "sha256": "3b5c90afb2ea8e8cc44cdec8e229352c806521c054dae6f4df28b99ba7f992d2",
          "sha1": "d5974a0c298f6e68375a38b82b70b8a9d23c74b7",
          "md5": "46b505c930adc4e2e1782f68a410d955"
        }
      ]
    }
  ]
}
